---
title: "CAMS: CAMS_DISCARD_MORTALITY_STOCK (Table)
#author: "K. Winiarski"
output:
  html_document: default
  github_document:
  pdf_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary


## Description

- **OUTPUT TABLE:** CAMS_GARFO.CAMS_DISCARD_MORTALITY_STOCK
- **YEARS:** N/A
- **RESOLUTION:** Discard mortality rates by species, gear and area
- **DEVELOPMENT LANGUAGE:** N/A
- **CODE:** N/A


## Information Sources



# ```{r table_flow0, echo=F,fig.height=3,fig.width=8, fig.cap="Figure 1.   CAMS_GARFO.CAMS_DISCARD_MORTALITY table lineage"}
# DiagrammeR::mermaid("
#   graph LR
#   NEFOP --> MAPS.CAMS_OBDBS_YYYY
#   ASM --> MAPS.CAMS_OBDBS_YYYY
#   MAPS.SECGEAR_MAPPED --> MAPS.CAMS_OBS_CATCH
#   MAPS.CAMS_CATCH --> MAPS.CAMS_OBS_CATCH
#   MAPS.CAMS_OBDBS_YYYY --> MAPS.CAMS_OBS_CATCH
# 
#         ")
# ```

## Approach


## Data Dictionary

```{r echo = F}

library(readxl)
library(knitr)

dat = readxl::read_xlsx('cams_discard_mortality_columns.xlsx')

kable(dat)

```

