---
title: "CAMS: MV_NEMIS_ALL_PTNS_EM_TRIPS_I"
#author: "Ben Galuardi"
output:
  html_document: default
  github_document:
  pdf_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(odbc)
library(ROracle)
library(dplyr, warn.conflicts = FALSE)

# # unlock keyring
# keyring::keyring_unlock("apsd_ma")
# 
# # local run
# # dw_apsd <- config::get(value = "apsd", file = "K:/R_DEV/config.yml")
# 
# # if on server..
# # dw_apsd <- config::get(value = "maps", file = "~/config.yml")
# 
# 
# # connect to MAPS
# 
# con_maps = apsdFuns::roracle_login(key_name = 'apsd_ma', key_service = 'maps')


```

```{r, include = FALSE, echo = FALSE}
Sys.setenv(TZ = "America/New_York")
Sys.setenv(ORA_SDTZ = "America/New_York")
  
if(file.exists(here::here("vignettes/articles", "pw.csv"))) {
  pw_df <- readr::read_csv(here::here("vignettes/articles", "pw.csv"), col_types = "c")
  pw <- pw_df$pw
} else {
  pw <- rstudioapi::askForPassword("Enter keyring password")
}

keyring::keyring_unlock("apsd_ma", password = pw) # will prompt for password
con_maps <- apsdFuns::roracle_login(key_name = 'apsd_ma', key_service = 'maps')
```

## Summary



## Description

- **OUTPUT TABLE:** MV_NEMIS_ALL_PTNS_EM_TRIPS_I
- **YEARS:** 2020+
- **RESOLUTION:** Trip
- **DEVELOPMENT LANGUAGE:** 
- **CODE:** https://github.com/NOAA-Fisheries-Greater-Atlantic-Region/discaRd/tree/model_estimator/CAMS


## Data Sources


```{r table_flow0, echo=F,fig.height=3,fig.width=8, fig.cap="Figure 1.   MV_NEMIS_ALL_PTNS_EM_TRIPS_I table lineage"}
DiagrammeR::mermaid("
  graph LR

        ")
```

## Approach



## Data Dictionary

```{r echo = F}
comments <- ROracle::dbGetQuery(con_maps, "SELECT * FROM all_col_comments WHERE owner = 'MAPS' AND table_name = 'MV_NEMIS_ALL_PTNS_EM_TRIPS_I'")

comments %>%
dplyr::select(
COLUMN = COLUMN_NAME,
DESCRIPTION = COMMENTS) %>%
knitr::kable(booktabs = TRUE) %>%
kableExtra::kable_styling(bootstrap_options = c("striped", 
"hover", "condensed", "responsive"),full_width = FALSE,position = "left", fixed_thead = TRUE,
font_size = 10)
```


