---
title: "CAMS: Yellowtail flounder in Calendar Year 2020"
author: "Ben Galuardi"
date: "`r Sys.Date()`"
output:
  html_document: default
  github_document:
  pdf_document: default
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, 
											message=FALSE, cache=FALSE,
											progress = TRUE, verbose = FALSE)

```

## Yellowtail flounder in Calendar Year 2020

```{r get data, echo = T}
library(ROracle)
library(tidyverse)
library(DT)

dw_apsd <- config::get(value = "maps", file = "~/config.yml")


con_maps <- ROracle::dbConnect(
	drv = ROracle::Oracle(),
	username = dw_apsd$uid,
	password = dw_apsd$pwd,  
	dbname = "NERO.world"
)

t1 = tbl(con_maps, sql("
	select fy
	, year
	, discard_source
	, STRATA_USED
	, tripcategory
	, scallop_area
	, max(cams_discard_rate)  cams_discard_rate
	, count(*)
	, sum(obs_kall) obs_kall
	, sum(subtrip_kall) subtrip_kall
	, sum(discard) discard
	, sum(discard)*0.00045359237 as dmt
	from (select * from CAMS_DISCARD_YELLOWTAILFLD_2018
	  union all
	  select * from CAMS_DISCARD_YELLOWTAILFLD_2019
	  	  union all
	  select * from CAMS_DISCARD_YELLOWTAILFLD_2020
	  	  union all
	  select * from CAMS_DISCARD_YELLOWTAILFLD_2021
	)
	where SPECIES_ITIS = 172909
	and species_stock = 'GB'
	and cams_gear_group = '132'
	and year in (2020)
	group by discard_source, tripcategory, scallop_area, fy, year	, STRATA_USED
	order by year, discard_source, tripcategory
											 ")) %>% 
	collect()
```


```{r, echo = F}

t1 %>% 
DT::datatable(., extensions = 'Buttons'
							 , options = list(dom = 'frtipB', buttons = c('csv', 'excel'), autoWidth = TRUE)
							, filter = "top"
							, class = 'cell-border stripe'
							, rownames = FALSE
) %>% 

							# , colnames = c('Year' = 1
							# 							 ,'Wind Energy Area' = 2
							# 							 , 'State Landed' = 3
							# 							 # , 'FMP' = 4
							# 							 , 'Nominal Value ($)' = 4
							# 							 , 'Landings (pounds*)' = 5
							# 							 , '% of Total State Nominal Value' = 6
							# 							 , '% of Total State Landed' = 7
							# 						   , 'GDP Deflator value (2019)' = 8
							# 							 , 'Value (2019 dollars)' = 9)
							# , caption = 'Table 2: State summary for all wind energy areas 2008-2019.') %>% 
	# # DT::formatCurrency(columns = 4, digits = 0) %>% 
	# DT::formatCurrency(columns = 9, digits = 0) %>%
	# DT::formatPercentage(columns = 8, digits = 2) %>% 	
	# DT::formatPercentage(columns = 6, digits = 0) %>% 
	# DT::formatPercentage(columns = 7, digits = 2) %>% 
	DT::formatRound(columns = 7, digits = 6) %>% 
	DT::formatRound(columns = 10:11, digits = 0) %>% 
			DT::formatRound(columns = 12, digits = 4)

```

