---
title: "groundfish loop: look at results"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r }
# evaluate groundfish results

# which geartypes have no discard source?

final_table %>%
	filter(is.na(DISCARD_SOURCE)) %>% 
	group_by(CAMS_GEAR_GROUP) %>% 
	dplyr::summarise(nvtr = n_distinct(VTRSERNO))


## primarily lobster pots. some shrimp trawls, then handlines and unknowns

# what is the discard rate for these trips?
res_list[[1]] %>%
	filter(is.na(DISCARD_SOURCE)) %>% 
	dplyr::select(
		DISCARD_SOURCE,
		CAMS_GEAR_GROUP,
		ACTIVITY_CODE_1,
		VTRSERNO,
		ARATE,
		CRATE,
		DISC_RATE,
		STRATA,
		STRATA_ASSUMED,
		LINK1,
		EST_DISCARD,
		DISCARD,
		OBS_DISCARD
	)

## no assumed rate because no obsevations
## changing the make these DISCARD_SOURCE = 'A' 



# make a smaller output table
dplyr::select(
	SPECIES_ITIS_EVAL,
	DISCARD_SOURCE,
	ACTIVITY_CODE_1,
	VTRSERNO,
	ARATE,
	CRATE,
	DISC_RATE,
	STRATA,
	STRATA_ASSUMED,
	LINK1,
	EST_DISCARD,
	DISCARD,
	OBS_DISCARD,
	eval(stratvars)
)

# --------------------------------------------
# Check Caless's results for EGB

# re-ran the haddock estimate
# recall the GEAR mathcing table had been updated

hadd = readRDS('discard_est_164744_gftrips_only.RDS')

hadd %>% 
	filter(substr(ACTIVITY_CODE_1, 1, 3) == 'NMS' &
									SPECIES_STOCK == 'EGB') %>% 
	group_by(DISCARD_SOURCE) %>% 
	dplyr::summarise(
										OBS_DISCARD = sum(OBS_DISCARD, na.rm = T),
										FINAL_DISCARD = sum(DISCARD, na.rm = T)
									)

# look by STRATA
hadd %>% 
	filter(substr(ACTIVITY_CODE_1, 1, 3) == 'NMS' &
				 	SPECIES_STOCK == 'EGB' & 
				 	SECTID == 3) %>% 
	group_by(STRATA) %>% 
	dplyr::summarise(
		OBS_DISCARD = sum(OBS_DISCARD, na.rm = T),
		FINAL_DISCARD = sum(DISCARD, na.rm = T)
	) %>% 
	knitr::kable()

# difference now much smaller

# A tibble: 3 x 3
# DISCARD_SOURCE OBS_DISCARD FINAL_DISCARD
# <chr>                <dbl>         <dbl>
# 	1 A                        0          880.
# 2 E                        0        66779.
# 3 O                    33926        33926
```


```{r look at strata from original table}

# original table
c_o_dat2 %>% 
	filter(SECTID == 3) %>% 
	group_by(GEARCODE, MESHGROUP, PERMIT_EFP_1, PERMIT_EFP_2, PERMIT_EFP_3, PERMIT_EFP_4, REDFISH_EXEMPTION
					 , SNE_SMALLMESH_EXEMPTION
					 , XLRG_GILLNET_EXEMPTION) %>% 
	dplyr::summarise(nobs = n_distinct(LINK1)) 


```

```{r ddat focal table}

ddat_focal %>% 
	filter(SECTID == 3) %>% 
	group_by(CAMS_GEAR_GROUP, MESHGROUP, PERMIT_EFP_1, PERMIT_EFP_2, PERMIT_EFP_3, PERMIT_EFP_4, REDFISH_EXEMPTION
					 , SNE_SMALLMESH_EXEMPTION
					 , XLRG_GILLNET_EXEMPTION) %>% 
	dplyr::summarise(nobs = n_distinct(LINK1), ntrips = n_distinct(VTRSERNO)) 


```




```{r strata from output}

# haddock output
hadd %>% 
	filter(SECTID == 3) %>% 
	group_by(eval(stratvars)) %>% 
# 	group_by(CAMS_GEAR_GROUP, MESHGROUP, PERMIT_EFP_1, PERMIT_EFP_2, PERMIT_EFP_3, PERMIT_EFP_4, REDFISH_EXEMPTION
#                                               , SNE_SMALLMESH_EXEMPTION
#                                               , XLRG_GILLNET_EXEMPTION) %>% 
	dplyr::summarise(nobs = n_distinct(LINK1)) %>% 
	knitr::kable()

```

```


