---
title: "DiscaRd steps for CAMS"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE, 
											message = FALSE, cache = FALSE,
											progress = TRUE, verbose = FALSE, comment = F
											, error = FALSE, dev = 'png', dpi = 200)
```

```{r setup, eval = F}

setwd("C:/Users/benjamin.galuardi/Documents/GitHub/discaRd")

library(odbc)
# library(RODBC)
library(dplyr, warn.conflicts = FALSE)
library(dbplyr)
library(ggplot2)
library(rgdal)
library(raster)
library(config)
library(stringr)

dw_apsd <- config::get(value = "apsd", file = "K:/R_DEV/config.yml")

bcon <- dbConnect(odbc::odbc(), 
									DSN = dw_apsd$dsn, 
									UID = dw_apsd$uid, 
									PWD = dw_apsd$pwd)


```

```{r get obs and catch data from oracle}

'%!in%' <- function(x,y)!('%in%'(x,y))

# get catch and matched obs data together

c_o_dat = tbl(bcon, sql("
	with obs as (
select link1
, nespp3
, discard
, NVL(sum(discard)/max(kept_all),0) as dk
, max(kept_all) obs_kall
from maps.BG_OBS_KALL_MOCK
-- where year = 2019
group by link1, nespp3, discard
)

select c.*
, o.nespp3
, o.discard
, o.obs_kall
, o.dk
from apsd.catch_link1_temp c
left join (
 select * from obs where nespp3 = 212 
) o
on o.link1 = c.link1
					")
)


odat2 = tbl(bcon, sql('
							with obs as (
							 select o.*
							, SUM(case when catdisp = 0 then o.hailwt else 0 end) OVER(PARTITION BY o.link3) as discard
							, SUM(o.hailwt) OVER(PARTITION BY o.link3) as obs_kall
							, substr(nespp4, 1, 3) as NESPP3
							from (
							 select * from apsd.BG_OBDBS_TABLES_5_2018
							 union all
							 select * from apsd.BG_OBDBS_TABLES_5_2019
							)
							 o
							)
					select c.*
						, o.*
						from apsd.catch_link1_temp c
						left join (
						 select * from obs where nespp3 = 212 
						) o
						on o.link1 = c.link1		
							
							'
							)) %>% 
	   dplyr::select(YEAR, LINK1, LINK3, AREA, DATELAND, DATESAIL, FISHDISP, CATDISP, GEARCAT, HAILWT, LIVEWT, OBS_KALL, DISCARD, NESPP4, NESPP3, NEGEAR,MESHSIZE, MESHGROUP, GEARTYPE, ACCESSAREA, VMSCODE) 




```

```{r subset obs trips for a species}

stat_area_sp = tbl(bcon, sql('select * from apsd.stat_areas_def')) %>% 
	filter(NESPP3 == '212') %>% 
	dplyr::select(STAT_AREA) %>% 
	distinct() %>% 
	collect()

# odat = c_o_dat %>% 
# 	filter(!is.na(LINK1) & NESPP3 == '212' & AREA %in% local(stat_area_sp[["stat_area"]])) %>% 
# 	group_by(YEAR, GEARCODE) %>% 
# 	summarise(dk_gear = sum(DISCARD, na.rm = T)/sum(OBS_KALL, na.rm = T))


# tbl(bcon, sql('select * from obdbs.OBMSZ@nova where year = 2019 and program <> 000')	)
# 
# tbl(bcon, sql('SELECT link1, link3, program, year, negear, codmsize, linermsize FROM obdbs.obotgh@nova where year = 2019 and program <> 000'))


stat_area_sp = tbl(bcon, sql('select * from apsd.stat_areas_def'))

dk_gear_mesh <- odat2 %>% 


# -------------------------------------------

dk_gear_mesh <- odat2 %>% 
	filter(!is.na(LINK1) & NESPP3 == 800 & AREA %in% local(stat_area_sp[["STAT_AREA"]]) ) %>% 
	group_by(YEAR, NEGEAR, MESHGROUP) %>% 
	summarise(dk_gear = sum(HAILWT, na.rm = T)/sum(OBS_KALL, na.rm = T)
						, OBS_KALL = sum(OBS_KALL, na.rm = T)
						) %>% 
	collect()


dk_gear_mesh %>% 
	tidyr::pivot_wider(values_from = 'dk_gear', names_from = 'NEGEAR') %>% 
	arrange(YEAR, MESHGROUP)
# ---------------------------------------------

```

```{r look at parking hauls within a subtrip byt matching gear and mesh}

h3dat <- tbl(bcon, sql('
	with obs as (
	--        select o.*
	select o.link3
	    , link1
	    , o.area as obs_area
	    , o.negear as obs_gear
	    , round(o.meshsize, 0) as obs_mesh
	    , o.meshgroup
	        , SUM(case when catdisp = 0 then o.hailwt else 0 end) OVER(PARTITION BY o.link3) as discard
	        , SUM(case when catdisp = 1 then o.hailwt else 0 end) OVER(PARTITION BY o.link3) as obs_haul_kall
	        , substr(nespp4, 1, 3) as NESPP3
	    from (
	        select * from apsd.BG_OBDBS_TABLES_5_2018
	        union all
	        select * from apsd.BG_OBDBS_TABLES_5_2019
	    )
	    o
	)
	    select c.*
	    , o.link3
	    , o.obs_area
	    , o.nespp3
	    , o.discard
	    , o.obs_haul_kall
	    , o.obs_gear 
	    , o.obs_mesh
	    , o.meshgroup
	from apsd.catch_link1_temp c
	    left outer join (
	        select * from obs -- where nespp3 = 212 
	    ) o
	on o.link1 = c.link1 AND c.mesh = o.obs_mesh											 
											 ')
	)


h3dat %>% 
	group_by(VTRSERNO, NESPP3) %>% 
	summarise(discard = sum(DISCARD, na.rm = T)
						)


```


```{r munge?}
cdat %>% 
	mutate(MESHGROUP = case_when(NEGEAR %in% c('054','057') ~ 'lg'
														)
				 , GEARTYPE = case_when( GEARTYPE == 'Unknown' & is.na(GEARTYPE) ~ 'Other'
				 					              , NESPP3 == 800 & GEARTYPE == 'Unknown' & is.na(GEARTYPE) ~ 'Scallop Dredge')
				 ) %>%
	filter(NESPP3 == 800) %>% 
	group_by(GEARTYPE, MESHGROUP) %>% 
	summarise(psum = sum(POUNDS, na.rm = T))

# UPDATE bg_total_landings_1 a
# SET a.geartype = 'Scallop Dredge'
# WHERE a.nespp3 = '800' 
# AND a.geartype = 'Unknown'
# AND a.gearcode IS NULL	
# /
# UPDATE bg_total_landings_1 a
# SET a.geartype = 'Other'
# WHERE a.geartype = 'Unknown'
# AND a.gearcode IS NULL	

```

