/*

move CAMS discard tables from MAPS to CAMS_GARFO

Ben Galuardi

Jan 28, 2022

Run from CAMS_GARFO

*/

DROP TABLE CAMS_GARFO.CAMS_STATAREA_STOCK
/

CREATE TABLE CAMS_GARFO.CAMS_STATAREA_STOCK as 
select *
from MAPS.CAMS_STATAREA_STOCK

/
DROP TABLE CAMS_GARFO.CAMS_DISCARD_MORTALITY_STOCK
/

CREATE TABLE CAMS_GARFO.CAMS_DISCARD_MORTALITY_STOCK as 
select *
from MAPS.CAMS_DISCARD_MORTALITY_STOCK

/
DROP TABLE CAMS_GARFO.CAMS_GEARCODE_STRATA
/

CREATE TABLE CAMS_GARFO.CAMS_GEARCODE_STRATA as 
select *
from MAPS.CAMS_GEARCODE_STRATA


/
DROP TABLE CAMS_GARFO.CAMS_MASTER_GEAR
/

CREATE TABLE CAMS_GARFO.CAMS_MASTER_GEAR as 
select *
from MAPS.CAMS_MASTER_GEAR

/

DROP TABLE CAMS_GARFO.CAMS_OBS_CATCH
/

CREATE TABLE CAMS_GARFO.CAMS_OBS_CATCH as 
select *
from MAPS.CAMS_OBS_CATCH

/

--DROP TABLE CAMS_CATCH
--/
--
--CREATE TABLE CAMS_CATCH as 
--select *
--from MAPS.CAMS_CATCH
--
--/
--DROP TABLE CAMS_OBS_PRORATE
--/
--
--CREATE TABLE CAMS_OBS_PRORATE as 
--select *
--from MAPS.CAMS_OBS_PRORATE
--
--/
--

--select *
--from maps.CFG_itis

BEGIN
FOR cur_rec IN (SELECT object_name, object_type
FROM user_objects
WHERE object_type IN
('TABLE'))
LOOP
BEGIN
EXECUTE IMMEDIATE 'GRANT SELECT ON '
--|| cur_rec.object_type
|| ' "'
|| cur_rec.object_name
|| '" TO JMOSER, APSD, SWIGLEY, GSHIELD, CLEGAULT, CAMS_GARFO_FOR_NEFSC';
EXCEPTION
WHEN OTHERS
THEN
DBMS_OUTPUT.put_line ( 'FAILED: DROP '
|| cur_rec.object_type
|| ' "'
|| cur_rec.object_name
|| '"'
);
END;
END LOOP;
END;
/